### ISSUE TITLE
Error en los test automáticos

### ISSUE THREAD

**Issue by pabcebrod** [DECIDEIO-CENSO/decideio-censo#7]
**Describe el bug**
Al pasar los test automáticos con el Travis CI se produce un error.

**Pasos seguidos**
Si quiere consultar todas las lineas de error debes entrar en Travis CI y te dejara ver el log completo.

**Comportamiento esperado**
El comportamiento esperado es que se completen los test con 0 errores.

**Capturas**

![image](https://user-images.githubusercontent.com/44404309/50163278-6744c200-02e0-11e9-8244-55e65e4e4c8c.png)

**Comment by ivagongar** [comment]
Ha aparecido un nuevo error al solucionar el anterior:

![photo5856989061686865792](https://user-images.githubusercontent.com/44404454/50549335-44f56180-0c5b-11e9-8e81-d64557d0a7b0.jpg)
