### ISSUE TITLE
Feature: API para obtener la lista de votaciones en las que puede participar un usuario

### ISSUE THREAD

**Issue by gbandres98** [DECIDEIO-CENSO/decideio-censo#9]
**¿Esta la propuesta relacionada con algún problema?.**
Desde el grupo de DecideIO-Cabina, nos vendría bien tener un método de la API en el que poder consultar todas las votaciones a las que tiene acceso un usuario determinado, para poder presentárselas en vez de pedirle el id de votación.

**Describa la solución**
Un método GET, al que se pasaría como cabecera de autenticación el token de un usuario logeado. El método deberá devolver una lista de votaciones en las que el usuario tiene permiso para participar (pertenece al censo). Por ejemplo:

Petición: 
`GET /census/user`
Respuesta:
`[
  {
    "id":123,
    "name":"Votación 123"
  },
  {
    "id":124,
    "name":"Votación 124"
  }
]`

**Información adicional**
En Django, se puede obtener información sobre el usuario autenticado de una petición mediante `request.user`, que devuelve un objeto User.

**Comment by pabcebrod** [comment]
Para llamar al método es necesario realizar la siguiente petición:
```GET /census/user/?user_id={}```
 enviándole el id del usuario del que queremos filtrar los votings.

Como respuesta se recibirá:
``` 'list_of_votings_id': [voting_id]```
 que tendrá formato json y será una lista de los id de los voting en los que puede participar el usuario.
